# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8316b8e2cc6116284fcee62791200fef6e142bc32bdc78a8fb039be82eefbe33f0b91e2cdc3a9889ffa60b70e1fe35586ee54ec555f7418dec48c23b865a9d16

test:
  secret_key_base: 2060edcb56a7ac36651430bd3e2073259eadc6c37b127d6f5bbcc636baf111782b23f90a530df2f0757257c1f9f2080677d2ed8b3dd21b05bce474b392093098

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
